### PR TITLE
Fix compilation and basic functionality on modern Macs.

### LINKED ISSUE #1: Mac build is broken/stale on modern Macs
Here's what I've found in my investigation:

- The COMPILING instructions are (as noted) old. wxMac has since been merged into wxWidgets proper, and w/ wxWidgets 3.1, we don't need a ton of special work. We can remove this file and fold it into the README with references to additional Mac-specific build flags as needed.
- The previous setup tried to support 32/64/native builds. 64-bit only builds require OS X 10.8 to run; we could support a fat build (native code for both 32- and 64- bit), but this would be at the expense of app size and unlikely to impact performance. So I'd suggest we only support a 32-bit build for maximum compatibility.
- wxWidgets 3.1 (needed for newer Mac builds) requires some updates. The fontpicker crashes due to invalid flag use (wxALIGN_CENTER_VERTICAL & wxEXPAND can't be combined); the patch files in wxpatches/ appear to be obsolete, as far as I can tell; we use __WXDEBUG__ to gate debug-only code, but as of [2.9.1](http://trac.wxwidgets.org/ticket/12251) this is actually always true, causing debug code to show up in release builds.
- On newer Macs, the default STL has changed in an incompatible way. For now, we can explicitly set the minimum supported version of macOS to 10.6 (Snow Leopard), which also resets to the older STL.
- --disable-lua doesn't actually disable all Lua code (and the Lua build will require more fixes; to be tracked separately).
- Font rendering is ugly on Retina displays

With all of these fixed, I was able to perform Debug/Release builds on macOS Sierra using wxWidgets 3.1.0 and --disable-lua. Patch coming shortly.

### PR DESCRIPTION
**Pull request by jpd236**
Fixes #1.

With this change, it is possible to build and run debug/release builds
of XWord on macOS Sierra, albeit only with --disable-lua. More work
may be needed to fix Lua support.

-Remove obsolete COMPILING instructions and update README to cover Mac
 builds.
-Always use 32-bit builds. 64-bit only builds require 10.8+; we could
 use a fat build, but that would increase the app size and this app
 isn't likely to benefit in terms of performance.
-One new assertion was causing crashes on Debug builds in
 src/dialogs/fontpicker.hpp; the wxALIGN_CENTER_VERTICAL flag is
 ignored when wxEXPAND is set, so omit it.
-Remove the wxwidgets patches which appear to be obsolete.
-Explicitly set the minimum OS X version to 10.6 (Snow Leopard). This
 fixes compilation on 10.9+ Macs where the default STL has changed.
-Gate more lua-based code behind --disable-lua to fix non-Lua builds.
-Fix font rendering on Retina displays (see Info.plist).
-Switch from __WXDEBUG__ to _DEBUG. As noted in
 http://trac.wxwidgets.org/ticket/12251, as of wxWidgets 2.9.1,
 __WXDEBUG__ is defined even in release builds as long as debug
 features are available in the library. This causes debug features of
 XWord to be enabled in the release configuration. Also fix compiler
 errors in release mode that resulted from this change.

### CODE REVIEW

**Comment by mrichards42** [comment]
Since I have only tried to build this on a mac a few times, and many years ago, whatever compiler options you think are appropriate are fine by me.

The files in wxpatches aren't strictly necessary, but MyAuiManager will be limited in functionality without them . . . in particular, the framemanager.h edits make a few of functions virtual that are overridden by MyAuiManager.  Having the entire file in there is silly though, they should really just be patches so that they aren't tied to a particular wx version.

I'll leave other comments on the commits themselves.

File: src/paths.cpp [hunk 1]
```diff
@@ -66,6 +66,7 @@ wxString GetConfigFile()
 //     wxStandardPaths::GetResourcesDir
 //     wxStandardPaths::GetAppDir
 // Fortunately these should always return the exe directory.
+// TODO: Investigate using wxStandardPaths::DontIgnoreAppSubDir with wxWidgets 2.9.1+
 #if defined(__WXDEBUG__) && defined(__WXMSW__)
```
Comment (jpd236) [inline src/paths.cpp]: Done.

FWIW, I put this TODO in as I wasn't sure whether you were okay going ahead with using wxWidgets 3.0+ across the board, so I wasn't sure we could rely on DontIgnoreAppSubDir being present. If we're comfortable with that, I suspect this whole code block could be simplified, as you could just turn off the logic that scans for debug/release in these paths. But I'd need to test on Windows to be sure, so I left it as is for now.

**Comment by jpd236** [comment]
Latest commit restores wxpatches/ as a single .patch file. I *think* I've isolated things to just the changes you actually intended, but do take a look and let me know if anything unintended is there. It applies cleanly to wxWidgets 3.1.0, at least.

As far as compiler options go - one thing I'll note is that I've been working towards getting a continuous build of this going via Travis CI, so you don't actually need a Mac to produce a build, and so the environment / compiler options are easily controlled and constant between builds. I have this in the "travis" branch at https://github.com/jpd236/xword/tree/travis, and the current config is at https://github.com/jpd236/xword/blob/travis/.travis.yml. You can see the current build status at https://travis-ci.org/jpd236/xword - this is a complete Mac debug/release build done automatically for each commit.

I'd like to make it faster by caching the wxWidgets dependency, add support for Linux builds (and perhaps Windows as well via AppVeyor), and have it be able to output the artifacts somewhere like GitHub Releases.

All in all, if you're in favor of this, it should make issuing releases for every OS easy, and should prevent the build from bit-rotting on any one OS, even if you don't personally use it on a daily basis. I'll keep tweaking at it and send a pull request when I've gotten further along. (But let me know if you have major concerns!)

**Comment by mrichards42** [comment]
I haven't looked at the patches yet, but I wanted to leave a comment on the travis stuff -- that sounds great!  It would definitely be worth looking into AppVeyor to get windows CI going too.

File: src/paths.cpp (hunk 1 above)
Comment (jpd236) [inline src/paths.cpp]: Would it be okay to defer that for a follow-up pull request? I'm afraid this one is getting a bit big, and I've had to stack more changes on top of it to avoid conflicts - naturally a lot of things depend on a working build as a baseline :)

The change you describe seems simple but I'd want to make sure it was working on all platforms before sending it out, and it feels a little out of scope of compilation fixes.

If not, LMK and I'll look into it here.

Comment (mrichards42) [inline src/paths.cpp]: That's fine -- this is getting to be a big PR.  I just have a couple things I want to test out to make sure they still work on windows.

**Comment by mrichards42** [comment]
Finally had a minute to go through everything and test on my end.  Looks good!

**Comment by jpd236** [comment]
Thanks for the review and merge!
